# Generated by Django 3.0.3 on 2024-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paakshala_project', '0011_auto_20240408_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateField(default='09-04-24'),
        ),
    ]
