# Generated by Django 3.0.3 on 2024-04-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paakshala_project', '0013_auto_20240411_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('type', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('website', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateField(default='21-04-24'),
        ),
    ]
