# Generated by Django 5.0.4 on 2024-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paakshala_project', '0014_auto_20240421_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateField(default='2024-04-25'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
