# Generated by Django 3.0.3 on 2024-04-05 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paakshala_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_on',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.CharField(default='0.5 kg', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
