# Generated by Django 3.0.3 on 2024-04-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paakshala_project', '0006_auto_20240408_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='items_list',
        ),
        migrations.AddField(
            model_name='user',
            name='categories_list',
            field=models.TextField(default=''),
        ),
    ]
