# Generated by Django 3.0.3 on 2024-04-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paakshala_project', '0010_auto_20240408_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateField(default='08-04-24'),
        ),
    ]
